### ISSUE TITLE
alpha release task list

### ISSUE THREAD

**Issue by cartazio** [hopper-lang/hopper#2]
- [ ] runtime system
  - [ ] evaluator
  - [ ] normalizer
  - [ ] baby GC (stop and copy model)
  - [ ] basic baby debugger info
- [ ] type checker
 - [ ] (co)inductive data types 
 - [ ] totality checking
 - [ ] positivity checking for composite data types
 - [ ] linear types
- [ ] module system
 - [ ] name space / linker representation
 - [ ] program "diff" outputs for escrow semantics, as "output" modules 
- [ ] support for different execution modes
 - [ ] embedded in an application (this is sortah a subclass of the db mode)
 - [ ] data base mode (first class ownership db!)
  - [ ] this may have a sibling modelling/simulation mode
 - [ ] normal programs with IO and stuff mode
 - [ ] agda style mode (this may or may not tie into the db mode, they're related)
- [ ] programming tools / UX
 - [ ] good error messages
  - [ ] localized blame for unification failures
  - [ ] spelling/namespace based suggestions for names that can't be resolved
  - [ ] stack traces 
  - [ ] profiling tools?
- [ ] sound metaprogramming / tactics based programming support (this may get punted to beta)
